### PR TITLE
Create benedikt.md

### PR DESCRIPTION
**Pull request by benekuehn**

### CODE REVIEW

**Comment by benekuehn** [comment]
This pr also solves #19

**Comment by jimbobbennett** [comment]
> This pr also solves #19

Ah, sweet! Will close my PR that does the same job.

**Comment by instafluff** [comment]
benedikt.md looks good to me but could someone take a look at the readme.md conflict please to resolve? Maybe @sguthals ?

**Comment by benekuehn** [comment]
@instafluff @sguthals solved the conflicts now. New Columns were created which weren't part of my commit.

**Comment by drguthals** [comment]
Awesome! Thanks! Yeah...I've been committing directly to master... (Not good practice @sguthals!!)

**Comment by drguthals** [comment]
Thanks for catching those `https` fixes!

**Pull request merged**
